version: '3.9'
services:
  backend:
    build: .
    ports:
      - '5243:80'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/instrumentdb
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    user: postgres
    restart: always
    environment:
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
